language: scala

matrix:
  include:
    - env: SBT_VERSION="1.2.8"
      jdk: openjdk8
    - env: SBT_VERSION="1.2.8"
      jdk: openjdk11
    - env: SBT_VERSION="1.3.4"
      jdk: openjdk8
    - env: SBT_VERSION="1.3.4"
      jdk: openjdk11

script:
  ## runs both regular tests and sbt-scripted integration tests
  - sbt -Dfile.encoding=UTF8 "^^ ${SBT_VERSION}" sbt-socco/scripted

sudo: false

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
